config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :show, :index, :create]
  resources :projects do 
     member do
      get :addusers
      get :removeuser
    end
  end  

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_and_belongs_to_many :users
	
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :email, presence: true, uniqueness: true
	validates :first_name, presence: true
	validates :last_name, presence: true
	has_and_belongs_to_many :projects

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  

	def index
		@projects = Project.all 
	end

	def addusers
	    @project = Project.find(params[:id])
	    @project.users << User.find(params[:user_id])
	    respond_to do |format|
	       format.html { redirect_to @project, :notice => 'Added.' }
	    end
  	end

  	def removeuser
     	  @project = Project.find(params[:id])
      	@user = User.find(params[:user_id])

      	if @user
         	@project.users.delete(@user)
      	end

      	respond_to do |format|
        	format.html { redirect_to @project, notice: 'User was successfully removed from Project' }
      	end
  	end

	def show
		@project = Project.find(params[:id])
		@users = User.all - @project.users
    @usersadd = @project.users.all
	end

	def new
		@project = Project.new
	end

	def create
    	@project = Project.new(project_params)
    	if @project.save
    		redirect_to @project
  		else
    		render 'new'
  		end
 	end

 	def project_params
 		params.require(:project).permit(:name, :active)
 	end	
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	helper_method :sort_column, :sort_direction
 	def index
		  @users = User.order(params[:sort])
		  @users = @users.to_a
		  @users.select! { |user| user.email.include?(params[:search].to_s) || user.first_name.include?(params[:search].to_s) ||  user.last_name.include?(params[:search].to_s) || user.projects.any? do |project| 
		  						project.name.include?(params[:search].to_s) 
		  					end}
		 

	end

	def show
		@user = User.find(params[:id])
	end

	def new
		@user = User.new
	end

	def create
    	@user = User.new(user_params)
    	if @user.save
    		redirect_to @user
  		else
    		render 'new'
  		end
 	end

 	private
 	def user_params
 		params.require(:user).permit(:first_name, :last_name, :email)
 	end	

  	def sort_column
    	User.column_names.include?(params[:sort]) ? params[:sort] : "first_name"
  	end
  
  	def sort_direction
    	%w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  	end
end

app/helpers/application_helper.rb
module ApplicationHelper



def sortable(column, title = nil)
  title ||= column.titleize
  css_class = column == sort_column ? "current #{sort_direction}" : nil
  direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
  link_to title, {:sort => column, :direction => direction}
end


end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstDay</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/index.html.erb
<table>
  	<thead>
    	<tr>
	      <th>Name</th>
      	  <th colspan="3"></th>
    	</tr>
  </thead>

  	<tbody>
		<% @projects.each do |project| %>
			<tr>
				<td> <%= project.name %> </td>
				<td><%= link_to 'Show', project %></td>
			</tr>
		<% end %>
	</tbody>
<table>
 

 <%= link_to "Create a new Project", new_project_path %><br>
 <%= link_to "Show Users", users_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>


<%= form_for(@project) do |f| %>
  
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label "Active" %><br>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>

  
<% end %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong> Name: </strong>
  <%= @project.name %>
</p>

<p>
  <strong>Is Active? </strong>
  <%= @project.active %>
</p>
	<table><h1> User</h1>
				  <thead>
				    	<tr>
				      		<th>Id</th>
				      		<th>Email</th>
				      		<th colspan="3"></th>
				    	</tr>
				  	</thead>
				  	<tbody>
  						<% @users.each do |user| %>
							<%= user.email %> <%= link_to 'Add friend', addusers_project_path(@project, user_id: user.id) %><br />
    					<% end %>
    				</tbody>
				  	<tbody>
					    <% @usersadd.each do |user| %>
					      <tr>
					        <td><%= user.id %></td>
					        <td><%= user.email %></td>
					        <td><%= link_to 'Remove user',  removeuser_project_path(@project, user_id: user.id) %></td>
					      </tr>
				    	<% end %>
				    </tbody>
				</table>

<%= link_to 'Back', projects_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/users/index.html.erb
<table>
  	<thead>
    	<tr>
	      <th><%= link_to "First name", sort: :first_name %></th>
	      <th><%= link_to "Last name", sort: :last_name %></th>
	      <th><%= link_to "Email", sort: :email %></th>
	      <th>Project </th>
      	  <th colspan="3"></th>
    	</tr>
  </thead>

  	<tbody>
		<% @users.each do |user| %>
			<tr>
				<td> <%= user.first_name %> </td>
				<td><%= user.last_name %></td>
				<td><%= user.email %></td>
				<td><% user.projects.each do |project| %>
						<% if project.active == true %>
							<%= project.name %>
						<% end %>	

					<% end %>
				</td>
			</tr>
		<% end %>
	</tbody>
<table>

<%= form_tag(users_path, method: :get, id: "search-form") do %>
<%= text_field_tag :search, params[:search], placeholder: "Search User" %><br>

<%= submit_tag "Search" %>
<% end %><br>
 

 <%= link_to "Create a new User", new_user_path %> <br>
  <%= link_to "Show all projects", projects_path %>

app/views/users/new.html.erb
<h1>New user</h1>


<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Back', users_path %>